# Generated by Django 4.2.7 on 2025-08-31 01:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bahan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_bahan', models.CharField(max_length=100)),
                ('harga_satuan', models.BigIntegerField()),
                ('satuan', models.CharField(default='kg', max_length=20)),
                ('keterangan', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Bahan',
                'db_table': 'bahan',
                'ordering': ['nama_bahan'],
            },
        ),
        migrations.CreateModel(
            name='HPP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.CharField(help_text='Format: YYYY-MM', max_length=7)),
                ('amount_total', models.BigIntegerField()),
                ('catatan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hpp_records', to='tenants.tenant')),
            ],
            options={
                'db_table': 'hpp',
                'ordering': ['-periode'],
                'unique_together': {('tenant', 'periode')},
            },
        ),
        migrations.CreateModel(
            name='HPPDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('harga_satuan', models.BigIntegerField()),
                ('subtotal', models.BigIntegerField()),
                ('bahan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hpp.bahan')),
                ('hpp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hpp_details', to='hpp.hpp')),
            ],
            options={
                'db_table': 'hpp_details',
            },
        ),
    ]
